# Acinetobacter baumannii AMR Phenotype Classifier: A Machine Learning Approach

In [1]:
import pandas as pd

In [2]:
genome_records = pd.read_csv("bv_brc_baumannii_genome_records.csv", low_memory=False)

amr_records = pd.read_csv("bv_brc_baumannii_amr_records.csv", low_memory=False)

In [3]:
genome_records['Genome ID'] = genome_records['Genome ID'].astype(object)

In [4]:
genome_records.info()

<class 'pandas.DataFrame'>
RangeIndex: 19704 entries, 0 to 19703
Data columns (total 90 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Genome ID             19704 non-null  object
 1   Genome Name           19704 non-null  str
 2   Other Names           0 non-null      float64
 3   NCBI Taxon ID         19704 non-null  int64
 4   Taxon Lineage IDs     19704 non-null  str
 5   Taxon Lineage Names   19704 non-null  str
 6   Superkingdom          19703 non-null  str
 7   Kingdom               19704 non-null  str
 8   Phylum                19704 non-null  str
 9   Class                 19704 non-null  str
 10  Order                 19704 non-null  str
 11  Family                19704 non-null  str
 12  Genus                 19704 non-null  str
 13  Species               19704 non-null  str
 14  Genome Status         19700 non-null  str
 15  Strain                18481 non-null  str
 16  Serovar               18 non-null     str
 17  Biovar                0 non-null      float64
 18  Pathovar              8 non-null      str
 19  MLST                  18524 non-null  str
 20  Segment               0 non-null      float64
 21  Subtype               0 non-null      float64
 22  H_type                0 non-null      float64
 23  N_type                0 non-null      float64
 24  H1 Clade Global       0 non-null      float64
 25  H1 Clade US           0 non-null      float64
 26  H5 Clade              0 non-null      float64
 27  pH1N1-like            0 non-null      float64
 28  Lineage               0 non-null      float64
 29  Clade                 0 non-null      float64
 30  Subclade              0 non-null      float64
 31  Other Typing          602 non-null    str
 32  Culture Collection    688 non-null    str
 33  Type Strain           4 non-null      str
 34  Reference             10 non-null     str
 35  Genome Quality        17392 non-null  str
 36  Completion Date       15981 non-null  str
 37  Publication           3330 non-null   str
 38  Authors               0 non-null      float64
 39  BioProject Accession  16841 non-null  str
 40  BioSample Accession   16856 non-null  str
 41  Assembly Accession    12952 non-null  str
 42  SRA Accession         2912 non-null   str
 43  GenBank Accessions    15990 non-null  str
 44  Sequencing Center     7388 non-null   str
 45  Sequencing Status     12488 non-null  str
 46  Sequencing Platform   15147 non-null  str
 47  Sequencing Depth      14874 non-null  str
 48  Assembly Method       14903 non-null  str
 49  Chromosome            0 non-null      float64
 50  Plasmids              1307 non-null   float64
 51  Contigs               19704 non-null  int64
 52  Size                  19704 non-null  int64
 53  GC Content            19700 non-null  float64
 54  Contig L50            19465 non-null  float64
 55  Contig N50            19485 non-null  float64
 56  TRNA                  19467 non-null  float64
 57  RRNA                  19033 non-null  float64
 58  Mat Peptide           0 non-null      float64
 59  CDS                   19704 non-null  int64
 60  Coarse Consistency    19486 non-null  float64
 61  Fine Consistency      19486 non-null  float64
 62  CheckM Contamination  6961 non-null   float64
 63  CheckM Completeness   19333 non-null  float64
 64  Genome Quality Flags  567 non-null    str
 65  Isolation Source      13238 non-null  str
 66  Isolation Comments    717 non-null    str
 67  Collection Date       16046 non-null  str
 68  Collection Year       15113 non-null  float64
 69  Season                0 non-null      float64
 70  Isolation Country     16341 non-null  str
 71  State/Province        1707 non-null   str
 72  County                0 non-null      float64
 73  City                  0 non-null      float64
 74  Geographic Group      13891 non-null  str
 75  Geographic Location   15784 non-null  str
 76  Other Environmental   67 non-null     str
 77  Host Name             14921 non-null  str
 78  Host Common Name      14619 non-null  str
 79  Host Sex              906 non-null    str
 80  Host Age              924 non-null    str
 81  Host Health           5858 non-null   str
 82  Host Group            14616 non-null  str
 83  Lab Host              0 non-null      float64
 84  Passage               2 non-null      str
 85  Other Clinical        488 non-null    str
 86  Additional Metadata   12634 non-null  str
 87  Comments              7548 non-null   str
 88  Date Inserted         19704 non-null  str
 89  Date Modified         19704 non-null  str
dtypes: float64(31), int64(4), object(1), str(54)
memory usage: 28.0+ MB

In [5]:
amr_records.info()

<class 'pandas.DataFrame'>
RangeIndex: 261495 entries, 0 to 261494
Data columns (total 21 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Taxon ID                          261495 non-null  int64
 1   Genome ID                         261495 non-null  float64
 2   Genome Name                       261494 non-null  str
 3   Antibiotic                        261494 non-null  str
 4   Resistant Phenotype               112298 non-null  str
 5   Measurement                       159709 non-null  str
 6   Measurement Sign                  11600 non-null   str
 7   Measurement Value                 160352 non-null  str
 8   Measurement Unit                  160352 non-null  str
 9   Laboratory Typing Method          13980 non-null   str
 10  Laboratory Typing Method Version  115 non-null     str
 11  Laboratory Typing Platform        9647 non-null    str
 12  Vendor                            43929 non-null   str
 13  Testing Standard                  12830 non-null   str
 14  Testing Standard Year             2562 non-null    float64
 15  Computational Method              245039 non-null  str
 16  Computational Method Version      238271 non-null  float64
 17  Computational Method Performance  245039 non-null  str
 18  Evidence                          260367 non-null  str
 19  Source                            43 non-null      float64
 20  PubMed                            4784 non-null    float64
dtypes: float64(5), int64(1), str(15)
memory usage: 73.4 MB

In [6]:
cols = genome_records.columns.tolist()

In [7]:
genome_records[cols[:18]].head(1)

,Genome ID,Genome Name,Other Names,NCBI Taxon ID,Taxon Lineage IDs,Taxon Lineage Names,Superkingdom,Kingdom,Phylum,Class,Order,Family,Genus,Species,Genome Status,Strain,Serovar,Biovar
0,1051623.3,Acinetobacter sp. V2,NaN,1051623,131567;2;3379134;1224;1236;2887326;468;469;196...,cellular organisms;Bacteria;Pseudomonadati;Pse...,Bacteria,Pseudomonadati,Pseudomonadota,Gammaproteobacteria,Moraxellales,Moraxellaceae,Acinetobacter,Acinetobacter sp. V2,WGS,V2,NaN,NaN

In [8]:
genome_records[cols[18:36]].head(1)

,Pathovar,MLST,Segment,Subtype,H_type,N_type,H1 Clade Global,H1 Clade US,H5 Clade,pH1N1-like,Lineage,Clade,Subclade,Other Typing,Culture Collection,Type Strain,Reference,Genome Quality
0,NaN,MLST.Acinetobacter_baumannii_2.557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good

In [9]:
genome_records[cols[36:54]].head(1)

,Completion Date,Publication,Authors,BioProject Accession,BioSample Accession,Assembly Accession,SRA Accession,GenBank Accessions,Sequencing Center,Sequencing Status,Sequencing Platform,Sequencing Depth,Assembly Method,Chromosome,Plasmids,Contigs,Size,GC Content
0,2015-04-10T00:00:00Z,NaN,NaN,PRJNA275383,SAMN03343989,GCF_001188385.1,NaN,JZFB00000000,University of KwaZulu Natal (Westville campus),WGS,Illumina HiSeq,109.2x,SOAPdenovo v. 2.04,NaN,NaN,16,4007850,38.15

In [10]:
genome_records[cols[54:72]].head(1)

,Contig L50,Contig N50,TRNA,RRNA,Mat Peptide,CDS,Coarse Consistency,Fine Consistency,CheckM Contamination,CheckM Completeness,Genome Quality Flags,Isolation Source,Isolation Comments,Collection Date,Collection Year,Season,Isolation Country,State/Province
0,2.0,466223.0,18.0,NaN,NaN,4101,99.3,94.1,5.6,99.7,NaN,oil contaminated soil,NaN,2007,2007.0,NaN,South Africa,NaN

In [11]:
genome_records[cols[72:]].head(1)

,County,City,Geographic Group,Geographic Location,Other Environmental,Host Name,Host Common Name,Host Sex,Host Age,Host Health,Host Group,Lab Host,Passage,Other Clinical,Additional Metadata,Comments,Date Inserted,Date Modified
0,NaN,NaN,Africa,South Africa: Amanzimtoti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sample_type:whole organism (Environmental),Species of Acinetobacter have been involved in...,2016-01-17T16:41:50.994Z,2016-01-17T16:41:50.994Z

In [12]:
genome_records['Genome Quality'].value_counts()

Genome Quality
Good    16825
Poor      567
Name: count, dtype: int64

In [13]:
genome_records['Isolation Source'].value_counts()

Isolation Source
sputum                                                                    2104
blood                                                                     1398
urine                                                                      492
wound                                                                      391
WOUND                                                                      237
                                                                          ...
human left leg at Walter Reed Army Medical Center, Washington, DC, USA       1
leg burn                                                                     1
conjunctiva                                                                  1
cerobrospinal fluid                                                          1
quinate enrichment from soil                                                 1
Name: count, Length: 1427, dtype: int64

### NOTE:
- In this current amr_records there isn't a way to filter only 'clinical' samples or genomes.
- But with thorough examination one might be able to differeniate.
- To keep this work minimal and easier I'm opting out and choosing all the records.

In [14]:
genome_records['MLST'].nunique()

1281

In [15]:
baumannii_strains = []
for species in genome_records['MLST'].unique().tolist():
    if "baumannii" in str(species):
        baumannii_strains.append(species)

In [16]:
len(set(baumannii_strains))

1273

In [17]:
genome_records = genome_records[
    (genome_records['MLST'].isin(baumannii_strains)) & 
    (genome_records['Genome Quality']=='Good') & 
    (genome_records['CheckM Completeness']>=95)]

In [18]:
genome_records.info()

<class 'pandas.DataFrame'>
Index: 15714 entries, 0 to 19703
Data columns (total 90 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Genome ID             15714 non-null  object
 1   Genome Name           15714 non-null  str
 2   Other Names           0 non-null      float64
 3   NCBI Taxon ID         15714 non-null  int64
 4   Taxon Lineage IDs     15714 non-null  str
 5   Taxon Lineage Names   15714 non-null  str
 6   Superkingdom          15714 non-null  str
 7   Kingdom               15714 non-null  str
 8   Phylum                15714 non-null  str
 9   Class                 15714 non-null  str
 10  Order                 15714 non-null  str
 11  Family                15714 non-null  str
 12  Genus                 15714 non-null  str
 13  Species               15714 non-null  str
 14  Genome Status         15714 non-null  str
 15  Strain                14895 non-null  str
 16  Serovar               14 non-null     str
 17  Biovar                0 non-null      float64
 18  Pathovar              6 non-null      str
 19  MLST                  15714 non-null  str
 20  Segment               0 non-null      float64
 21  Subtype               0 non-null      float64
 22  H_type                0 non-null      float64
 23  N_type                0 non-null      float64
 24  H1 Clade Global       0 non-null      float64
 25  H1 Clade US           0 non-null      float64
 26  H5 Clade              0 non-null      float64
 27  pH1N1-like            0 non-null      float64
 28  Lineage               0 non-null      float64
 29  Clade                 0 non-null      float64
 30  Subclade              0 non-null      float64
 31  Other Typing          503 non-null    str
 32  Culture Collection    637 non-null    str
 33  Type Strain           4 non-null      str
 34  Reference             10 non-null     str
 35  Genome Quality        15714 non-null  str
 36  Completion Date       12502 non-null  str
 37  Publication           2939 non-null   str
 38  Authors               0 non-null      float64
 39  BioProject Accession  13358 non-null  str
 40  BioSample Accession   13380 non-null  str
 41  Assembly Accession    11392 non-null  str
 42  SRA Accession         2785 non-null   str
 43  GenBank Accessions    12511 non-null  str
 44  Sequencing Center     6553 non-null   str
 45  Sequencing Status     11443 non-null  str
 46  Sequencing Platform   11896 non-null  str
 47  Sequencing Depth      11679 non-null  str
 48  Assembly Method       11686 non-null  str
 49  Chromosome            0 non-null      float64
 50  Plasmids              831 non-null    float64
 51  Contigs               15714 non-null  int64
 52  Size                  15714 non-null  int64
 53  GC Content            15714 non-null  float64
 54  Contig L50            15695 non-null  float64
 55  Contig N50            15714 non-null  float64
 56  TRNA                  15714 non-null  float64
 57  RRNA                  15420 non-null  float64
 58  Mat Peptide           0 non-null      float64
 59  CDS                   15714 non-null  int64
 60  Coarse Consistency    15714 non-null  float64
 61  Fine Consistency      15714 non-null  float64
 62  CheckM Contamination  5246 non-null   float64
 63  CheckM Completeness   15714 non-null  float64
 64  Genome Quality Flags  0 non-null      str
 65  Isolation Source      10274 non-null  str
 66  Isolation Comments    593 non-null    str
 67  Collection Date       12751 non-null  str
 68  Collection Year       11863 non-null  float64
 69  Season                0 non-null      float64
 70  Isolation Country     12999 non-null  str
 71  State/Province        1608 non-null   str
 72  County                0 non-null      float64
 73  City                  0 non-null      float64
 74  Geographic Group      10712 non-null  str
 75  Geographic Location   12436 non-null  str
 76  Other Environmental   55 non-null     str
 77  Host Name             12204 non-null  str
 78  Host Common Name      11995 non-null  str
 79  Host Sex              762 non-null    str
 80  Host Age              799 non-null    str
 81  Host Health           4460 non-null   str
 82  Host Group            11993 non-null  str
 83  Lab Host              0 non-null      float64
 84  Passage               0 non-null      str
 85  Other Clinical        390 non-null    str
 86  Additional Metadata   9896 non-null   str
 87  Comments              6694 non-null   str
 88  Date Inserted         15714 non-null  str
 89  Date Modified         15714 non-null  str
dtypes: float64(31), int64(4), object(1), str(54)
memory usage: 22.6+ MB

In [19]:
genome_records['Sequencing Status'].value_counts()

Sequencing Status
WGS         10816
Complete      627
Name: count, dtype: int64

In [20]:
amr_records['Laboratory Typing Method'].value_counts()

Laboratory Typing Method
Broth dilution              11596
Disk diffusion               2195
Computational Prediction      105
MIC                            74
Agar dilution                  10
Name: count, dtype: int64

In [21]:
amr_records['Laboratory Typing Platform'].value_counts()

Laboratory Typing Platform
BD Phoenix               3645
VITEK 2                  3605
MicroScan                1701
BD Phoenix NMIC/ID133     267
E-test                    119
AdaBoost Classifier       105
Sensititre GNX2F          100
Sensititer                 39
Phoenix                    28
Vitek II                   24
Microscan                  10
Broth microdilution         3
Sensititre                  1
Name: count, dtype: int64

In [22]:
amr_records['Measurement Unit'].value_counts()

Measurement Unit
mg/L    160195
mm         157
Name: count, dtype: int64

In [23]:
amr_records = amr_records[
    (amr_records['Genome ID'].isin(genome_records['Genome ID'])) & 
    (amr_records['Measurement Unit']=='mg/L') &
    (amr_records['Evidence']=='Laboratory Method') &
    (amr_records['Testing Standard'].isin(['CLSI', 'clsi']))
    ]
    
amr_records.info()

<class 'pandas.DataFrame'>
Index: 9563 entries, 6 to 261427
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Taxon ID                          9563 non-null   int64
 1   Genome ID                         9563 non-null   float64
 2   Genome Name                       9563 non-null   str
 3   Antibiotic                        9563 non-null   str
 4   Resistant Phenotype               9145 non-null   str
 5   Measurement                       9563 non-null   str
 6   Measurement Sign                  9275 non-null   str
 7   Measurement Value                 9563 non-null   str
 8   Measurement Unit                  9563 non-null   str
 9   Laboratory Typing Method          9371 non-null   str
 10  Laboratory Typing Method Version  0 non-null      str
 11  Laboratory Typing Platform        8621 non-null   str
 12  Vendor                            8689 non-null   str
 13  Testing Standard                  9563 non-null   str
 14  Testing Standard Year             356 non-null    float64
 15  Computational Method              0 non-null      str
 16  Computational Method Version      0 non-null      float64
 17  Computational Method Performance  0 non-null      str
 18  Evidence                          9563 non-null   str
 19  Source                            0 non-null      float64
 20  PubMed                            691 non-null    float64
dtypes: float64(5), int64(1), str(15)
memory usage: 2.7 MB

In [24]:
amr_records['Laboratory Typing Method'].value_counts()

Laboratory Typing Method
Broth dilution    9371
Name: count, dtype: int64

In [25]:
amr_records.head(1)

,Taxon ID,Genome ID,Genome Name,Antibiotic,Resistant Phenotype,Measurement,Measurement Sign,Measurement Value,Measurement Unit,Laboratory Typing Method,...,Laboratory Typing Platform,Vendor,Testing Standard,Testing Standard Year,Computational Method,Computational Method Version,Computational Method Performance,Evidence,Source,PubMed
6,470,470.1556,Acinetobacter baumannii strain MRSN20315,gentamicin,Resistant,>8,>,8,mg/L,Broth dilution,...,BD Phoenix,BD,CLSI,NaN,NaN,NaN,NaN,Laboratory Method,NaN,25824815.0

In [26]:
amr_records['Measurement Sign'].value_counts()

Measurement Sign
>     3938
>=    2352
=     1928
<=    1057
Name: count, dtype: int64

In [27]:
amr_records[amr_records['Antibiotic'].str.endswith('enem')]['Antibiotic'].value_counts()

Antibiotic
imipenem     622
meropenem    242
doripenem    117
ertapenem     10
Name: count, dtype: int64

In [28]:
amr_records[amr_records['Antibiotic'].str.endswith('enem')]['Genome ID'].nunique()

677

In [29]:
amr_records[amr_records['Antibiotic'].str.endswith('enem')]['Measurement Sign'].value_counts()

Measurement Sign
=     342
<=    251
>     211
>=     92
Name: count, dtype: int64

In [30]:
# List of carbapenem antibiotics of interest
carbapenems = ['imipenem', 'meropenem', 'doripenem', 'ertapenem']

# -------------------------------------------------------------------
# Filter AMR records for carbapenem-related antibiotics
# Using `.copy()` avoids chained assignment issues downstream
# -------------------------------------------------------------------
carbapenem_data = (
    amr_records.loc[
        amr_records['Antibiotic'].str.endswith('enem', na=False)
    ].copy()
)

# -------------------------------------------------------------------
# Identify genomes originating from India
# `na=False` prevents errors if location contains missing values
# -------------------------------------------------------------------
indian_genome_records = (
    genome_records.loc[
        genome_records['Geographic Location'].str.startswith('India', na=False)
    ].copy()
)

# -------------------------------------------------------------------
# Summary statistics
# -------------------------------------------------------------------
n_indian_genomes = indian_genome_records['Genome ID'].nunique()
n_carbapenem_genomes = carbapenem_data['Genome ID'].nunique()

print(f'Indian genomes: {n_indian_genomes}')
print(f'Carbapenem-associated genomes: {n_carbapenem_genomes}')

# -------------------------------------------------------------------
# Exclude Indian genomes from training and test dataset
# These genomes will be used post the model is build (production phase)
# -------------------------------------------------------------------
indian_genome_ids = set(indian_genome_records['Genome ID'])

indian_carbapenem_data = carbapenem_data[carbapenem_data['Genome ID'].isin(indian_genome_ids)]

carbapenem_data = (
    carbapenem_data.loc[
        ~carbapenem_data['Genome ID'].isin(indian_genome_ids)
    ].copy()
)

Indian genomes: 427
Carbapenem-associated genomes: 677

In [31]:
# Build the summary
rows = []
for ab in carbapenems:
    subset = carbapenem_data[carbapenem_data['Antibiotic'] == ab]
    sign_counts = subset['Measurement Sign'].value_counts()
    rows.append({
        'Antibiotic':       ab,
        '= (exact)':        sign_counts.get('=',  0),
        '<= (left-cens.)':  sign_counts.get('<=', 0),
        '> (right-cens.)':  sign_counts.get('>',  0),
        '>= (right-cens.)': sign_counts.get('>=', 0),
        'Total Records':    len(subset),
        'Unique Genome IDs': subset['Genome ID'].nunique()
    })

summary_df = pd.DataFrame(rows).set_index('Antibiotic')

In [32]:
summary_df

,= (exact),<= (left-cens.),> (right-cens.),>= (right-cens.),Total Records,Unique Genome IDs
Antibiotic,,,,,,
imipenem,192,198,100,55,620,548
meropenem,94,30,62,37,240,239
doripenem,55,23,36,0,114,114
ertapenem,1,0,9,0,10,10

In [33]:
# Exclude carbapenem (class-level, no drug specificity)
# Focus on records WITH a Resistant Phenotype label

for ab in ['imipenem', 'meropenem', 'doripenem', 'ertapenem']:
    subset = carbapenem_data[carbapenem_data['Antibiotic'] == ab]
    
    has_phenotype = subset['Resistant Phenotype'].notna().sum()
    has_mic       = subset['Measurement Sign'].notna().sum()
    phenotype_dist = subset['Resistant Phenotype'].value_counts().to_dict()
    
    print(f"\n{ab.upper()}")
    print(f"  Records with phenotype label : {has_phenotype}")
    print(f"  Records with MIC measurement : {has_mic}")
    print(f"  Phenotype distribution       : {phenotype_dist}")
    print(f"  Unique Genome IDs            : {subset['Genome ID'].nunique()}")

IMIPENEM
  Records with phenotype label : 541
  Records with MIC measurement : 545
  Phenotype distribution       : {'Susceptible': 339, 'Resistant': 166, 'Intermediate': 36}
  Unique Genome IDs            : 548

MEROPENEM
  Records with phenotype label : 217
  Records with MIC measurement : 223
  Phenotype distribution       : {'Susceptible': 101, 'Resistant': 93, 'Intermediate': 23}
  Unique Genome IDs            : 239

DORIPENEM
  Records with phenotype label : 108
  Records with MIC measurement : 114
  Phenotype distribution       : {'Susceptible': 77, 'Resistant': 30, 'Intermediate': 1}
  Unique Genome IDs            : 114

ERTAPENEM
  Records with phenotype label : 3
  Records with MIC measurement : 10
  Phenotype distribution       : {'Resistant': 2, 'Intermediate': 1}
  Unique Genome IDs            : 10

In [34]:
# =============================================================================
# COLLAPSE INTERMEDIATE (I) + RESISTANT (R) → NON-SUSCEPTIBLE (NS)
# Terminology follows Hicks et al. (2019), which explicitly defines
# Non-Susceptibility (NS) as the combined I + R category for clinical
# AMR binary classification — used in their A. baumannii analysis.
#
# Clinical justification: For carbapenems, both Intermediate and Resistant
# MICs exceed achievable serum concentrations under standard dosing regimens.
# The clinical question is not "is this resistant?" but "is this susceptible?"
# Any organism that is not clearly Susceptible is Non-Susceptible (NS).
# =============================================================================

# Define target antibiotics (ertapenem excluded — insufficient labeled data)
target_carbapenems = ['imipenem', 'meropenem', 'doripenem']

# Work on a copy to preserve the original carbapenem_data intact
modeling_data = carbapenem_data[
    carbapenem_data['Antibiotic'].isin(target_carbapenems) &
    carbapenem_data['Resistant Phenotype'].notna()
].copy()

# -----------------------------------------------------------------------------
# Collapse: Intermediate → Non-Susceptible
#           Resistant    → Non-Susceptible
#           Susceptible  → Susceptible (unchanged)
#
# Explicit mapping of all three source classes avoids silent passthrough
# and makes the collapse intent unambiguous to any reader of the code.
# -----------------------------------------------------------------------------
phenotype_map = {
    'Resistant'    : 'Non-Susceptible',
    'Intermediate' : 'Non-Susceptible',
    'Susceptible'  : 'Susceptible'
}

modeling_data['Binary Label'] = modeling_data['Resistant Phenotype'].map(phenotype_map)

# Confirm only two classes remain
print("Unique labels after collapse:")
print(modeling_data['Binary Label'].unique())

# -----------------------------------------------------------------------------
# Verify no unmapped values slipped through (would appear as NaN)
# -----------------------------------------------------------------------------
unmapped = modeling_data['Binary Label'].isna().sum()
assert unmapped == 0, (
    f"{unmapped} records could not be mapped — "
    f"check for unexpected Resistant Phenotype values: "
    f"{modeling_data.loc[modeling_data['Binary Label'].isna(), 'Resistant Phenotype'].unique()}"
)
print("Assertion passed: all records successfully mapped to S / NS.\n")

# -----------------------------------------------------------------------------
# Per-antibiotic class distribution after collapse
# -----------------------------------------------------------------------------
print("Class distribution after I + R → Non-Susceptible collapse:\n")

summary_rows = []

for ab in target_carbapenems:
    subset = modeling_data[modeling_data['Antibiotic'] == ab]
    counts = subset['Binary Label'].value_counts()
    n_total          = len(subset)
    n_susceptible    = counts.get('Susceptible',     0)
    n_nonsusceptible = counts.get('Non-Susceptible', 0)
    pct_s  = round(100 * n_susceptible    / n_total, 1)
    pct_ns = round(100 * n_nonsusceptible / n_total, 1)

    # Breakdown of what went into NS (for traceability)
    orig_counts = subset['Resistant Phenotype'].value_counts()
    n_r = orig_counts.get('Resistant',    0)
    n_i = orig_counts.get('Intermediate', 0)

    summary_rows.append({
        'Antibiotic'              : ab,
        'Susceptible (n)'         : n_susceptible,
        'Non-Susceptible (n)'     : n_nonsusceptible,
        '  of which Resistant'    : n_r,
        '  of which Intermediate' : n_i,
        'Total (n)'               : n_total,
        'Susceptible (%)'         : pct_s,
        'Non-Susceptible (%)'     : pct_ns,
        'Unique Genome IDs'       : subset['Genome ID'].nunique()
    })

    print(f"{ab.upper()}")
    print(f"  Susceptible      : {n_susceptible:>4}  ({pct_s}%)")
    print(f"  Non-Susceptible  : {n_nonsusceptible:>4}  ({pct_ns}%)")
    print(f"    ↳ Resistant    : {n_r:>4}")
    print(f"    ↳ Intermediate : {n_i:>4}")
    print(f"  Total            : {n_total:>4}")
    print(f"  Unique Genomes   : {subset['Genome ID'].nunique()}\n")

summary_collapse_df = pd.DataFrame(summary_rows).set_index('Antibiotic')
print(summary_collapse_df)

# -----------------------------------------------------------------------------
# Sanity check: confirm Intermediate has been fully absorbed into NS
# -----------------------------------------------------------------------------
residual_intermediate = (modeling_data['Binary Label'] == 'Intermediate').sum()
assert residual_intermediate == 0, (
    "Intermediate records still present — collapse failed."
)
print("\nAssertion passed: no Intermediate records remain in Binary Label.")

Unique labels after collapse:
<ArrowStringArray>
['Susceptible', 'Non-Susceptible']
Length: 2, dtype: str
Assertion passed: all records successfully mapped to S / NS.

Class distribution after I + R → Non-Susceptible collapse:

IMIPENEM
  Susceptible      :  339  (62.7%)
  Non-Susceptible  :  202  (37.3%)
    ↳ Resistant    :  166
    ↳ Intermediate :   36
  Total            :  541
  Unique Genomes   : 469

MEROPENEM
  Susceptible      :  101  (46.5%)
  Non-Susceptible  :  116  (53.5%)
    ↳ Resistant    :   93
    ↳ Intermediate :   23
  Total            :  217
  Unique Genomes   : 216

DORIPENEM
  Susceptible      :   77  (71.3%)
  Non-Susceptible  :   31  (28.7%)
    ↳ Resistant    :   30
    ↳ Intermediate :    1
  Total            :  108
  Unique Genomes   : 108

            Susceptible (n)  Non-Susceptible (n)    of which Resistant  \
Antibiotic
imipenem                339                  202                   166
meropenem               101                  116                    93
doripenem                77                   31                    30

              of which Intermediate  Total (n)  Susceptible (%)  \
Antibiotic
imipenem                         36        541             62.7
meropenem                        23        217             46.5
doripenem                         1        108             71.3

            Non-Susceptible (%)  Unique Genome IDs
Antibiotic
imipenem                   37.3                469
meropenem                  53.5                216
doripenem                  28.7                108

Assertion passed: no Intermediate records remain in Binary Label.

In [35]:
selected_columns = ['Genome ID', 'Genome Name', 'Antibiotic', 
                    'Measurement', 'Measurement Sign', 'Measurement Value', 
                    'Evidence', 'Resistant Phenotype', 'Binary Label']

modeling_data = modeling_data[selected_columns].reset_index(drop=True)

In [36]:
modeling_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 866 entries, 0 to 865
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Genome ID            866 non-null    float64
 1   Genome Name          866 non-null    str
 2   Antibiotic           866 non-null    str
 3   Measurement          866 non-null    str
 4   Measurement Sign     866 non-null    str
 5   Measurement Value    866 non-null    str
 6   Evidence             866 non-null    str
 7   Resistant Phenotype  866 non-null    str
 8   Binary Label         866 non-null    str
dtypes: float64(1), str(8)
memory usage: 139.7 KB

In [37]:
modeling_data.head()

,Genome ID,Genome Name,Antibiotic,Measurement,Measurement Sign,Measurement Value,Evidence,Resistant Phenotype,Binary Label
0,470.7771,Acinetobacter baumannii strain MRSN7347,imipenem,1,<=,1,Laboratory Method,Susceptible,Susceptible
1,470.8004,Acinetobacter baumannii strain MRSN7699,imipenem,1,<=,1,Laboratory Method,Susceptible,Susceptible
2,470.7715,Acinetobacter baumannii strain MRSN7267,imipenem,2,=,2,Laboratory Method,Susceptible,Susceptible
3,470.7505,Acinetobacter baumannii strain MRSN11811,imipenem,4,=,4,Laboratory Method,Susceptible,Susceptible
4,470.7445,Acinetobacter baumannii strain MRSN11716,meropenem,0.5,=,0.5,Laboratory Method,Susceptible,Susceptible

In [38]:
modeling_data['Genome ID'].nunique()

579

In [39]:
modeling_data['Genome ID'].value_counts()

Genome ID
470.7505    4
470.1551    3
470.7529    3
470.7512    3
470.7784    3
           ..
470.7429    1
470.7382    1
470.7755    1
470.7341    1
470.7418    1
Name: count, Length: 579, dtype: int64

In [40]:
modeling_data[modeling_data['Genome ID']==470.7505]

,Genome ID,Genome Name,Antibiotic,Measurement,Measurement Sign,Measurement Value,Evidence,Resistant Phenotype,Binary Label
3,470.7505,Acinetobacter baumannii strain MRSN11811,imipenem,4,=,4,Laboratory Method,Susceptible,Susceptible
151,470.7505,Acinetobacter baumannii strain MRSN11811,imipenem,0.5,=,0.5,Laboratory Method,Susceptible,Susceptible
295,470.7505,Acinetobacter baumannii strain MRSN11811,doripenem,1,=,1,Laboratory Method,Susceptible,Susceptible
425,470.7505,Acinetobacter baumannii strain MRSN11811,meropenem,0.5,=,0.5,Laboratory Method,Susceptible,Susceptible

In [41]:
modeling_data[modeling_data['Genome ID']==470.1551]

,Genome ID,Genome Name,Antibiotic,Measurement,Measurement Sign,Measurement Value,Evidence,Resistant Phenotype,Binary Label
32,470.1551,Acinetobacter baumannii strain MRSN16896,imipenem,==1,=,1,Laboratory Method,Susceptible,Susceptible
555,470.1551,Acinetobacter baumannii strain MRSN16896,meropenem,==1,=,1,Laboratory Method,Susceptible,Susceptible
577,470.1551,Acinetobacter baumannii strain MRSN16896,imipenem,==2,=,2,Laboratory Method,Susceptible,Susceptible

In [42]:
modeling_data[modeling_data['Antibiotic']=='doripenem']['Binary Label'].value_counts()

Binary Label
Susceptible        77
Non-Susceptible    31
Name: count, dtype: int64

In [43]:
genome_ids = modeling_data['Genome ID'].unique().tolist()

with open("carbapenem_baumannii_genomes.txt", "w") as f:
    for gid in genome_ids:
        f.write(str(gid).strip() + "\n")

In [44]:
indian_genome_ids = indian_carbapenem_data['Genome ID'].unique().tolist()

with open("indian_carbapenem_baumannii_genomes.txt", "w") as f:
    for gid in indian_genome_ids:
        f.write(str(gid).strip() + "\n")

In [45]:
print(len(genome_ids), len(indian_genome_ids))

579 3

In [46]:
failed_genomes = pd.read_csv('/Users/akshayonly/Main/Scripts/bioinformatics/AMR/src/pipeline/failed_genomes.txt', sep='\t', names=['Genome ID', 'Log'])

In [47]:
modeling_data[(modeling_data['Antibiotic']=='doripenem') & (modeling_data['Genome ID'].isin(failed_genomes['Genome ID']))]['Binary Label'].value_counts()

Binary Label
Susceptible    2
Name: count, dtype: int64

In [48]:
modeling_data['Antibiotic'].value_counts()

Antibiotic
imipenem     541
meropenem    217
doripenem    108
Name: count, dtype: int64

In [49]:
modeling_data[(modeling_data['Antibiotic']=='imipenem') & (modeling_data['Genome ID'].isin(failed_genomes['Genome ID']))]['Binary Label'].value_counts()

Binary Label
Susceptible        17
Non-Susceptible     8
Name: count, dtype: int64

In [50]:
modeling_data[(modeling_data['Antibiotic']=='imipenem') & (~modeling_data['Genome ID'].isin(failed_genomes['Genome ID']))]['Binary Label'].value_counts()

Binary Label
Susceptible        322
Non-Susceptible    194
Name: count, dtype: int64

In [51]:
modeling_data[(modeling_data['Antibiotic']=='meropenem') & (modeling_data['Genome ID'].isin(failed_genomes['Genome ID']))]['Binary Label'].value_counts()

Binary Label
Non-Susceptible    6
Susceptible        5
Name: count, dtype: int64

In [52]:
modeling_data[(modeling_data['Antibiotic']=='meropenem') & (~modeling_data['Genome ID'].isin(failed_genomes['Genome ID']))]['Binary Label'].value_counts()

Binary Label
Non-Susceptible    110
Susceptible         96
Name: count, dtype: int64

In [53]:
modeling_data[(modeling_data['Antibiotic']=='doripenem') & (~modeling_data['Genome ID'].isin(failed_genomes['Genome ID']))]['Binary Label'].value_counts()

Binary Label
Susceptible        75
Non-Susceptible    31
Name: count, dtype: int64

In [54]:
modeling_data.to_csv('/Users/akshayonly/Main/Scripts/bioinformatics/AMR/data/baumannii/baumannii_modeling_data.csv', index=False)